windows-nsis/build
This adds a --sign-digest option to the windows-nsis/build script, to
be able to specify the digest used when signing binaries.
Note that this also changes the default digest from SHA1 to SHA256.
Signed-off-by: Steffan Karger <steffan.karger@fox-it.com>
=> Add support to windows-nsis/build to specify signing digest

windows-nsis/build
Signed-off-by: Steffan Karger <steffan@karger.me>
=> Add missing line continuation in windows-nsis/build

generic/build.vars
--enable-password-save --disable-snappy are not supported in openvpn-2.3.10
=> remove obsolete configure options

generic/README
Just did a fresh build by following step-by-step openvpn-build instructions, compiled on win 64 via cygwin.
Got the simple error that make wasn't installed.
=> Add make to cygwin packages

.travis.yml
travis-ci allows automation of pull request build testing
=> travis-ci config

windows-nsis/build, windows-nsis/build-complete, windows-nsis/build-complete.vars, windows-nsis/openvpn.nsi
This PR ensures that the Windows installer installs openvpnserv2.exe alongside openvpnserv.exe. Registering openvpnserv2.exe a Windows service is not implemented yet, because registration fucntionality [is missing](https://github.com/xkjyeah/openvpnserv2/issues/4) from openvpnserv2.
v2: Remove openvpnserv2.exe on uninstall
=> Add installation of openvpnserv2.exe to Windows installers

windows-nsis/openvpn.nsi
This PR makes the install script to register openvpnserv2 as a Windows system service. For this change to make sense the code for the old openvpnserv.exe needs to be modified slightly - that will be fixed in another patch. Right now openvpnserv2 sets its StartupType to "automatic", which is not what we want, and which needs to be fixed. That fix is, however, unrelated to this PR.
=> Register openvpnserv2 as a service during install

generic/build, generic/build.vars
```
R00-2+jenkins@r00-2 ~/openvpn-build/generic
$  IMAGEROOT=`pwd`/image-win32 CHOST=i686-w64-mingw32 CBUILD=i686-pc-cygwin ./build
./build: line 77: cd: /home/jenkins/openvpn-build/generic/sources: No such file or directory
FATAL: Cannot download http://www.oberhumer.com/opensource/lzo/download/lzo-2.09.tar.gz
R00-2+jenkins@r00-2 ~/openvpn-build/generic
$
```
=> fix build in case no wget is installed (using curl)

generic/build.vars
Previously the installers generated using "master" branch in openvpn-build would
not work properly. With this change all the components (openvpn, openvpnserv,
openvpn-gui) work in unison. In addition build should work out of the box
without any modifications of build.vars or build-complete.vars.
=> Use more reasonable build parameters in build.vars

windows-nsis/openvpn.nsi
If the command succeeds, it outputs lots of diagnostic stuff, as if it had
errored out. This change takes the return code of the command and produces a
short, informational message based on it.
=> Make output of "sc.exe start OpenVPNServiceInteractive" less verbose

windows-nsis/INSTALL-win32.txt, windows-nsis/openvpn.nsi
For "release/2.3" branch the original _INSTALL-win32.txt_ is ok ("nobody has complained so far"). For the "master" branch INSTALL-win32.txt was migrated and modernized earlier, in [PR#35](https://github.com/OpenVPN/openvpn-build/pull/35)
=> Migrate INSTALL-win32.txt from OpenVPN "release/2.3" to openvpn-build

windows-nsis/build-snapshot
URL: https://github.com/OpenVPN/openvpn-build/issues/39
=> Fix wrong OPENVPN_VERSION default in build-snapshot

windows-nsis/openvpn.nsi
This is required to get the registry keys deleted during uninstall on 64 bit platforms.
=> Check bitness in uninstaller for correct Registry view

windows-nsis/openvpn.nsi
- Interactive service is useful for launching openvpn without elevated
privileges (using GUI or otherwise), so install it as a part of
openvpn.exe and dependencies.
- Global config and log directories, sample configs and shortcut
for creating tls-auth key are also generally useful. Set up these
too on installing openvpn.exe.
- The automatic service (openvpnserv2) is kept optional, selected by
default.
- Check for running openvpn instances after (not before) removing
services. This reduces the chance of the installer exiting because
openvpn is running.
=> Install interactive service and sample configs as a part of the core

windows-nsis/openvpn.nsi
As discussed in the IRC meeting of Dec 7 and under Issue 59:
- Install "user-space", dlls, iservice by default
- Service (openvpnserv2), GUI, TAP can be selected/unselected
(selected by default)
- EasyRSA is optional (unselected by default)
- Add-to-path, add-shortcuts, launch-on-logon and file-asociation
grouped into advance options (selected by default)
- If Service is not selected, openvpnserv2 is not removed, only stopped
It is now possible to unselect service, GUI, TAP in any combination
and still have a working setup using previously installed versions
of those components. However, lack of an installed version of TAP will
cause services not to startup -- this is not checked or warned against.
All hidden and displayed sections may be selected/unselected from the
command line but …
=> Simplifiy user choices and always install openvpn, dlls and services

windows-nsis/openvpn.nsi
As the openvpn installation path is always overwritten by the installer, overwriting the exe_path makes sense. Without this some installations will be broken causing the GUI to fail with "CreateProcess openvpn.exe --version" failed etc..
=> Always overwrite executable path in registry

windows-nsis/openvpn.nsi
- Add a registry key "HKLM\Software\OpenVPN\disable_save_passwords" and
set it to 0 by default. The key is left unchanged if already present.
- The default behaviour may be changed during installation.
For silent install use /SELECT_DISABLE_SAVEPASS=1 to set the key to 1.
- If the key is present and set to a non-zero value, the installer
will not change it back to zero: either uninstall before re-install or
edit the registry directly.
As discussed in #75 
=> Add a disable password save section to installer

windows-nsis/openvpn.nsi
From user perspective it was not clear what certificate management scripts the installer provided. Even if the user knew the installer contained EasyRSA, there was no clear indication of whether it was EasyRSA 3 (=easy-rsa on our GitHub page) or EasyRSA 2 (=easy-rsa-old).
=> Clarify that the certificate management scripts refer to EasyRSA 2

windows-nsis/openvpn.nsi
This entry is optional as it is only used to override the default
value of "OpenVPN Administrators". However, in its absence, the service
logs an error indicating a missing registry key. Adding the registry entry
during installation prevents the error message and also provides a place
holder for users who want to customize the name of the admin group.
Trac: #892
=> Add a registry entry for ovpn_admin_group set to its default value

.travis.yml, generic/build
depcache was broken since "set -e" was added to generic/build
this PR resolves that and enables depcache build on travis-ci
=> Fix depcache build

.travis.yml, generic/build
addresses https://github.com/OpenVPN/openvpn-build/issues/111
=> include missing win32 libraries when using static built openssl

windows-nsis/build
Any value given to this arg will print the usage instead of being passed to
osslsigncode.
bug introduced in commit 0e3868e5
Signed-off-by: Gert van Dijk <gert@gertvandijk.net>
=> Actually accept a given value to --sign-digest in windows-nsis/build

.appveyor.yml, generic/patches/pkcs11-helper-001-RFC7512.patch
added patch from https://github.com/OpenSC/pkcs11-helper/pull/4
=> Add "PKCS#11 URIs compliant with RFC7512" patch

.appveyor.yml
APPVEYOR_PROJECT_SLUG point to project path properly, when
repo is cloned, deleted and cloned again
=> AppVeyor: use proper way to resolve project path, also some cleanup

generic/build
openssl-1.1.0 produces bigger output
we rarely want to look at it (unless it fails), also longish output breaks travis-ci (it is limited to 4Mb logs)
https://travis-ci.org/OpenVPN/openvpn-build/jobs/332279790
=> supress openssl build log

.travis.yml
openssl-1.1.0 is default already, no need for separate build anymore
=> travis-ci: remove not needed openssl-1.1.0 build

generic/build
OpenSSL 1.1.1a needs an explicit make command for the build to succeed.
Also reverse the test for the version and use the older install method
for OpenSSL 1.0.* method and the new one for everything else.
=> Add support for building with OpenSSL 1.1.1a

README.rst, generic/build.vars, generic/patches/openssl-1.1.0j-issue7653.patch
Building OpenSSL 1.1.0j with mingw-w64 fails unless we patch the
makefile on the fly. The patch will not apply cleanly to OpenSSL 1.1.1,
so documentation was added to make note of it, as well as for the
openvpn-build patch management system in general.
URL: https://github.com/openssl/openssl/issues/7653
=> Prepare for OpenVPN 2.4.7 (version change, openssl-1.1.0j patch)

.appveyor.yml, generic/build, windows-nsis/build-complete
It turns out that we haven't had any optimization
enabled for mingw Windows build, and, for example,
Visual Studio generated code was significantly faster.
This turns optimization on, and according to
performance tests, it increases download bandwidth
by up to 20% and now we're on par with Visual Studio.
Signed-off-by: lstipakov@gmail.com <lstipakov@gmail.com>
=> generic/build: use -O2 optimization

msvc/build-env.bat
This fixes download URLs for pkcs11 and p7zip.
Signed-off-by: Lev Stipakov <lstipakov@gmail.com>
=> msvc: fix dependencies URLs

msvc/README, msvc/build.bat
Commit d77611 to openvpn made life easier for developers
by eliminating additional copy step, but broke openvpn-build.
Also update msvc build instructions.
=> msvc: fix msvc build system and update instructions

windows-nsis/openvpn.nsi
When there are no TAP-Windows6 adapters present, the tap0901 driver's service is not (and cannot be) started. This prevents all OpenVPN services from starting. The no-TAP-Windows6/Wintun adapters present situation is checked at run-time.
=> windows-nsis: Remove service dependency on tap0901

.appveyor.yml, README.rst, msvc/README, msvc/build-env.bat, msvc/build.bat
As openvpn's repo already switched MSVC to VS2019, the openvpn-build should follow.
=> Upgrade to Visual Studio 2019

windows-nsis/build, windows-nsis/build-complete, windows-nsis/build-complete.vars, windows-nsis/openvpn.nsi
This adds "wintun" option to Windows installer,
which installs wintun driver and creates tun device.
Wintun installer is based on wintun's "msi-example" -
a wrapper over MSM - wintun's official distribution way.
=> windows-nsis: add wintun support

.appveyor.yml, generic/build
PKG_CHECK_MODULES macro is used to check the presence of given packages
and, if found, sets variables FOO_CFLAGS and FOO_LIBS, where FOO is a package
name and _CLAGS and _LIBS values are taken from package config, for example
from /lib/x86_64-linux-gnu/pkgconfig/liblz4.pc
Setting PKG_CONFIG to 'true' doesn't make much sense, since it makes
PKG_CHECK_MODULES to assume that any package is installed without any checks
and without setting FOO_CFLAGS/LIBS values.
This breaks, for example, Windows MinGW build on Windows build machine,
since it assumes the presence of liblz4 and enables callinf LZ4 API.
Because LZ4_LIBS is not set, we got linker errors.
Fix by removing PKG_CONFIG assignment to 'true'.
=> build: fix Windows MinGW build

msvc/build-env.bat, msvc/build.bat
Previously we had 64bit hardcoded. This change allows
to build dependencies and openvpn for 32bit as well:
set ARCH=32&& build.bat
Default architecture is still 64.
=> msvc: support for 32bit architecture

generic/build.vars, windows-nsis/build-complete
We used to have -O2 optimization for binaries in NSIS installer
https://github.com/OpenVPN/openvpn-build/pull/153/commits/7402da3e54dea03c628b4440b9b01ab33b694b66
but it was implemented in ./build-complete, which is not used when
building binaries for MSI installer.
Add O3 flag to EXTRA_TARGET_CFLAGS, which is then used as
CFLAGS when building all binaries.
This also fixes missing optimization for openssl builds. Before OpenSSL 1.1.1,
openssl ignored CFLAGS env variabe and used its own value, which included O3.
Starting from 1.1.1, OpenSSL uses CFLAGS if it has been defined.
https://github.com/openssl/openssl/commit/0342e42d864b7a670b4403389df057c4da6d7975
Since we have defined CFLAGS without O3, we didn't use optimization when
building OpenSSL.
Before this fix there was no O3 in compiler …
=> Enable O3 optimization for Windows binaries

windows-msi/artwork/license.txt, windows-msi/build.wsf, windows-msi/msi.wxs, windows-msi/script/Builder.js, windows-msi/version.m4
Bundle content of EasyRSA3 Windows release
except openssl binaries. While it downloads content of
64bit release, it also works for win32, since architecture
is relevant only for openssl binaries, which we don't use.
Create EasyRSA-Start.bat, which is used to start
easyrsa shell and adds openvpn's bin directory to the PATH
to make easyrsa use openssl bundled with openvpn.
=> Upgrade to EasyRSA3

windows-msi/msi.wxs
- fix manual page start menu link not to be
deleted on uninstall
- fix creation of "configuration samples" shortcut
to non-existing directory when "configuration samples"
feature wasn't selected for installation
This fixes https://github.com/OpenVPN/openvpn-build/issues/193
Reported-by: Marc Becker
=> msi: bookkeeping

windows-nsis/build-snapshot
Same issue as during [last version change](/OpenVPN/openvpn-build/commit/2eac27).
Was updated in OpenVPN repo [2020-08-12](/OpenVPN/openvpn/commit/f7432a9).
Error got masked due to previous problems with missing manpage (fixed by installing [python-docutils](/OpenVPN/openvpn-build/commit/ecc9771)).
=> Bump OpenVPN version for snapshot build

windows-msi/msi.wxs
Currently reboot is scheduled by calling MsiSetMode() in deferred
custom action ProcessDeferredAction. This approach doesn't work.
Invoke CheckAndScheduleReboot immediate custom action which
schedules reboot. The action code is a part of openvpn project.
=> msi: properly schedule reboot in the end of installation

generic/build
On Windows cross-built OpenSSL loads config at path
c:\etc\ssl\openssl.conf, which is writable by non-admin user.
This could be a security risk, so disable config autoload.
=> generic/build: disable config autoload for OpenSSL

windows-msi/msi.wxs
- Context menu: verb="import", description = "Import the VPN config"
- Also make "import" the default "verb". That is, double clicking on
an ovpn file will import it instead of opening in an editor.
When an .ovpn file is downloaded it can be automatically imported
if the browser is set to open the file instead of saving it.
If the GUI is not installed, the "import" verb is not added
and "open" will automatically become the default. As per MSDN,
"open" has precedence over others when there is no explicit
default and no verb order is specified. This preserves the
current behaviour.
=> Add a context menu item to .ovpn files for importing to the GUI

windows-msi/build.wsf, windows-msi/msi.wxs
Patch https://patchwork.openvpn.net/patch/2293/ links LZO statically,
so we don't need LZO DLL anymore.
=> msi: remove LZO dll

windows-msi/README.rst, windows-msi/build-and-package.ps1, windows-msi/vcpkg-ports/readme.txt
- Support openssl 1.1.1 and 3.x builds
- Ensure that all dependencies are installed, upgraded and
integrated in case something in provisioning failed or
dependencies have changed
- Reorder some commands so they make more sense
=> windows-msi: fixes and improvements to build-and-package.ps1

generic/patches/pkcs11-helper-001-RFC7512.patch
@kalev updated [pkcs11-helper](https://src.fedoraproject.org/rpms/pkcs11-helper/commits/master)  version and patch for Fedora.
Mirroring the patch update is to fulfill the ["do what Fedora does"](https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg19814.html) policy and have a *synchronized* state for current `pkcs11-helper`.
The patch used in Fedora is now (again) equivalent to taking commits directly from the respective [GitHub pull request](https://github.com/OpenSC/pkcs11-helper/pull/4.patch) changes.
Applying the new patch results in exactly the same changes to `pkcs11-helper` source code (minus the line offset warnings for versions after `v1.22` while doing so).
supersedes #203.
=> update pkcs11-helper patch to match Fedora version

.github/workflows/build.yaml
Without delay or with small delay packets may arrive
in different order or blocked because they could be mistaken
for port scan. Use 500ms delay to try to avoid it.
=> GitHub Actions: use longer delay with port knocking

windows-msi/msi.wxs, windows-msi/script/Service.js
As we don't support "Modify" action, adding OpenVPNService
is problematic since it requires uninstall and reinstall.
Install it by default. For clean install, use "Manual"
start mode and doesn't start it. For upgrade, preserve existing
configuration - for example if start mode was "automatic" and service
was started - the same will apply for the new installation.
This allows to remove code from openvpnmsica.dll which
reads service status, but doesn't apply it to the new installation.
=> OpenVPNService: install by default and keep previous state

.github/workflows/build.yaml
To enable upgrade of MSI snapshots, produce
installers with unique product code and incremental product version (2.6.x), where x is per-workflow
automatically incremented GITHUB_RUN_NUMBER.
=> GitHub Actions: automatic versioning

windows-msi/build.wsf, windows-msi/msi.wxs
Since https://github.com/OpenVPN/openvpn-gui/pull/518 has been merged, user can provide provide credentials and manually start VPN before logon.
Add PLAP dll and reg files to "OpenVPN Service"
feature. The reg files are required to manage PLAP registration from GUI app.
Add "Enable OpenVPN Pre-Logon Access Provider"
feature, which performs PLAP registration (creating certain registry keys) during installation.
=> Add PLAP feature

windows-msi/version.m4
Update Easy-RSA download source: OpenVPN/easy-rsa Release v3.1.1
Add new comment to clarify:
The 64bit version of Easy-RSA is suitable for
both 32bit and 64bit OpenVPN-Windows-MSI-Installers.
Note:
OpenSSL binaries from Easy-RSA zip file are not used by Openvpn-build. Openvpn-build uses OpenSSL binaries from vcpkg port.
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>
=> windows-msi/version.m4: Update Easy-RSA to v3.1.1

.github/workflows/build.yaml
After building MSI, run t_client tests from
openvpn-windows-test repo.
This launches Windows 2022 EC2 instance,
copies and installs 64bit MSI and runs various
connection tests agains existing backend infrastructure.
See
https://github.com/OpenVPN/openvpn-windows-test/blob/master/Start-LocalTest.ps1
for tests details.
=> Add t_client Windows tests

.github/workflows/build.yaml
Test backend doesn't allow multiple connections with the same CN, so prevent running t_client aws tests in parallel.
=> Prevent concurrent run of t_client tests

windows-msi/version.m4
MSFT has deprecated cross-signing and therefore
Windows 7 driver is signed incorrectly. While we
settle the signing issue, revert driver to 9.24.6.
=> Revert tap-windows to 9.24.6

windows-msi/build.wsf, windows-msi/msi.wxs, windows-msi/script/PlapReg.js
openvpn-plap-install.reg has install path hardcoded, which breaks when OpenVPN is installed to non-default location.
Add 2 custom action:
- GetInstallDir to get install path
- UpdatePlapReg to update openvpn-plap-install.reg
Second action is deferred and runs under elevated privileges,
so it is able to modify files at installation path.
=> Write actual install path into openvpn-plap-install.reg

.github/workflows/build.yaml
The latest Windows runner has Visual Studio 2022 installed.
=> msvc: update to Visual Studio 2022

windows-msi/build.wsf, windows-msi/script/Service.js
Instead of using "manual" start type,
start service by default for clean installs.
=> Start service by default

windows-msi/sign-openvpn.bat
The x86 DLLs of `openvpn-gui` in `v2.6_rc1` did NOT get signed due to this.
Arguments to `signtool` stopped after `openvpn-gui.exe`.
Not sure what happens when the script tries to execute the (PLAP?) DLL (next command) , but it's definitely not what has been intended.
=> Fix line continuation issue in sign-openvpn.bat

windows-msi/build.wsf, windows-msi/doc/config/Where are my config files.txt.in, windows-msi/msi.wxs, windows-msi/script/Service.js
When configs are migrated from config to config-auto, create a text file in config directory with explanation.
Remove this file on uninstall.
=> Configs migration: add note to user

windows-msi/script/ActiveSetupCA.js
Starting from 2.5, "Run on logon" installer feature didn't work in cases when ProductCode of new version is "less" than ProductCode in old version in in alphanumeric comparison.
- Install version with product code 456
- Log off and log on so that ActiveSetup command will be added to HKCU
- Install version with product code 123
- Log off and log on
Here openvpn-gui won't be run, because:
- ActiveSetup command from product 123 will be executed, which adds openvpn-gui to Windows\CurrentVersion\Run
- ActiveSetup command from product 456 will be executed, which removes openvpn-gui from Windows\CurrentVersion\Run
To fix that, we use ">OpenVPN_UserSetup" as ActiveSetup command name, which is guaranteed to be run after all GUID name, similar to NSIS implementation …
=> ActiveSetup: fix "Run on logon" behavior

.github/workflows/build.yaml
Works around current breakage of WiX download server (see wixtoolset/issues#7159).
=> GHA: download WiX from different download location.

windows-msi/build.wsf, windows-msi/msi.wxs, windows-msi/version.m4
ovpn-dco installation logic has been moved into MSM so that it can be reused by Connect and both openvpn-gui and Connect could co-exist and use the same driver.
=> Install ovpn-dco from MSM

debian-sbuild/packaging/focal/debian/NEWS, debian-sbuild/packaging/focal/debian/rules
Establishing DCO compatiblity is more important than trying to be compatible with setups that depend on --enable-iproute2.
Related to OpenVPN/openvpn-build#333
=> debian-sbuild: remove --enable-iproute2 for Ubuntu focal (20.04LTS)

windows-msi/msi.wxs
We configure openvpn service (set startup mode and run, if needed) only on installation or upgrade. This is achieved by running configuration custom action with "NOT Installed" condition.
However the product may be reinstalled (even though we disable it in UI), for example when pushed via AD Group Policy or with command line
msiexec /fomusv "OpenVPN-2.6.2-I001-amd64.msi" /L*V reinstall.log
In this case OpenVPN service status is set to "disabled", since our configuration custom action won't be run.
Fix by changing action condition to NOT REMOVE, which covers both install/upgrade and reinstall cases.
Fixes https://github.com/OpenVPN/openvpn-build/issues/348
Change-Id: I92974dea4749c415e25ab0f804050e3e6d309ffc
=> msi: configure OpenVPN Service also on reinstall

windows-msi/build.wsf, windows-msi/msi.wxs
The current implementation doesn't work well when the first column of "reg query" output contains two words (example from UA/RU):
C:\Users\diach>REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE" /ve
HKEY_LOCAL_MACHINE\SOFTWARE
(po umolchaniyu)    REG_SZ
Workaround this by adding a registy key "bin_dir", in which case we don't care about two-worded values anymore.
PS C:\Users\lev> REG QUERY HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN /v bin_dir
HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN
bin_dir    REG_SZ    C:\Program Files\OpenVPN\bin\
Fixes https://github.com/OpenVPN/openvpn-build/issues/352
Change-Id: I00114438a61a498535d5d7e143df8a115d655a97
=> msi/easyrsa: fix openssl path search on non-English Windows

windows-msi/build.wsf
The build script assumed that the sample files in
openvpn were checked out with LF line-endings. Since these files have no eol enforced by .gitattributes in openvpn, this depends on core.autocrlf=false, which is not the default on Windows.
So assume that these files will be checked out with CRLF line endings on Windows. The alternative would be to enforce LF line-endings via openvpn's
.gitattributes.
Fixes #358
=> windows-msi: don't depend on core.autocrlf=false

.github/workflows/build.yaml
Latest vcpkg openssl port broken right now.
See https://github.com/microsoft/vcpkg/pull/31171
=> GHA: use vcpkg submodule without updating to latest

windows-msi/msi.wxs
Enable for
openvpn.exe, openvpn-gui.exe and openvpnserv.exe
Dumps are stored by default at %LOCALAPPDATA%\CrashDumps
With .PDBs we can analyze those and figure out crash causes.
Change-Id: I9bd70a5aeb10bd86e9138d226a84081c16191bd1
=> msi: enable dumps collection for openvpn processes

windows-msi/version.m4
Easy-RSA version 3.1.5 introduces a new method, called 'RAW', to generate a CA with a password, without writing that password to the disk.  This is done by handing over all password inputs to the SSL binary.  Easy-RSA does not interfere with the password.
Omit Easy-RSA version 3.1.4:
Easy-RSA version 3.1.4 use of file-descritors proved to be of no value. This is because use of file-descriptors results in temp files being written to disk.
Omit Easy-RSA version 3.1.3:
Easy-RSA version 3.1.3 is unable to build a CA using Windows, due to use of file-descriptors, which OpenSSL built for Windows does not support.
Easy-RSA ChangeLog has further details.
=> Bump Easy-RSA to version 3.1.5

.github/workflows/build.yaml
I want to handle updating them automatically, but for that we need to pin them to exact versions, first.
Related to #380 (Renovate support).
=> GHA: make all action versions explicit (release/2.6)

windows-msi/build.wsf, windows-msi/version.m4
So that we can in the next step than manage updates with renovate. Commented annotations are modelled after regex manager examples from renovate documentation.
Related to #380 (Renovate Support).
=> windows-msi: For files from GitHub releases factor out version number

.github/renovate-config.json, .github/workflows/build.yaml, .github/workflows/depgraph.yaml, .github/workflows/renovate.yaml, renovate.json, windows-msi/build.wsf, windows-msi/version.m4
Add basic support to track dependencies:
* On git submodules
* On GitHub actions
* On GitHub releases in version.m4
All functionality has been tested in flichtenheld/openvpn-build.
This PR also merged the required changes from release/2.6 to master.
Closes: #380
=> Renovate Support

.github/workflows/build.yaml
Previously we checked out the current remote state of the submodule branch. This was required for the builds triggered remotely by openvpn changes.
Now that we have renovate to trigger builds on submodule remote changes we do not need this anymore. And it actually hurts since the PR builds do not actually test the changes in the PR in some cases.
=> GHA: check out the actual state of the submodules

windows-msi/build.wsf
The addition of `'%*'` allows EasyRSA-Start.bat to pass all command line options on to EasyRSA initialisation: 'sh.exe easyrsa-shell-init.sh %*'.
There is no specific use case here, simply that the batch file will pass options as expected.
Further patches for a new "Windows Start Menu item" can take advantage of this by passing along a new "non-admin" option.
=> Easy-RSA: Allow 'EasyRSA-Start.bat' to pass command line options

.github/workflows/build.yaml
We need to have ability to tag the builds.
New release flow tries to tag openvpn-gui
if this tag does not exist.
Before that was done manually.
=> GHA: git: configure user name and email

windows-msi/script/ACL.js
Group names are localized in some localizations, so we have to use SIDs.
Fixes https://github.com/OpenVPN/openvpn-build/issues/671.
=> msi: use SIDs instead of built-in group names

.github/workflows/renovate.yaml
- openvpn3 already has a renovate config which is usually handled by a differente renovate instance, but it is still useful to get PR builds for this in GitHub to verify the GHA updates directly.
- openvpn doesn't have renovate, yet, so we need to do onboarding first. See https://gerrit.openvpn.net/c/openvpn/+/722
=> Renovate: Also check other repositories

.github/workflows/build.yaml
All scp actions seem to be a bit shit, judging
by the issues people report.
Just use scp directly. Didn't bother to support
a keyphrase though.
Fixes: OpenVPN/openvpn-build#774
=> GHA: Use scp manually instead of through action

.github/workflows/build.yaml
Requires installing dh-dkms since dkms support moved to that package.
Require a work-around for running sg which will fail by default on Ubuntu 24.04 runners.
Also hard-code the Ubuntu version. Renovate will tell us when there is a new runner available and we can switch at our own pace.
=> GHA: Fix building Debian packages on Ubuntu 24.04 runner

.github/workflows/build.yaml
This allows us to remove the concurrency setting
so we can wait longer for an available runner.
=> GHA: Use a self-hosted runner for t_client tests

windows-msi/version.m4
By default, Renovate uses semantic versioning, which assumes versions follow the format X.Y.Z. However, openvpnserv2 uses 4-part versions like 1.4.0.1 and 2.0.0.0.
This commit tells Renovate to use versioning=loose, which accepts versions with any number of dot-separated segments and compares them correctly.
=> msi: use loose versioning for openvpnserv2 in Renovate

windows-msi/build.wsf, windows-msi/msi.wxs
Commit
42bf901 ("msi: change log directory for persistent connections")
changed log directory for persistent connections, but haven't explicitly added permissions to virtual service account running those connections.
This adds missing permissions.
Github: #942
Reported-by: Jernej Simončič
=> msi: fix service log directory permissions

windows-msi/msi.wxs
is installed
When service is not installed, its viirtual service account is not created and permission setting fails.
GitHub: #963
=> msi: set log directory permission for service account only when service

.github/workflows/build.yaml
See https://github.com/actions/download-artifact/issues/419
=> GHA: download-artifact v5

windows-msi/build.wsf, windows-msi/msi.wxs
This is required so that the messages in event log from the interactive service are displayed in "General" tab.
GitHub: https://github.com/OpenVPN/openvpn/issues/842
=> msi: add registered message file
