windows-nsis/openvpn.nsi
URL: http://thread.gmane.org/gmane.network.openvpn.devel/11176
=> Always include tap-windows, openvpn-gui and easy-rsa in the installer

windows-nsis/openvpn.nsi
Trac #632
Tested-by: Fish Wang <fish.thss@gmail.com>
Tested-by: Jan Just Keijser <janjust@nikhef.nl>
=> Fail if trying to run I60x installer on Windows XP

windows-nsis/INSTALL-win32.txt, windows-nsis/openvpn.nsi
Migrate INSTALL-win32.txt from the OpenVPN project and modernize it.
=> Migrate INSTALL-win32.txt from the OpenVPN project and modernize it.

windows-nsis/openvpn.nsi
- This adds an active-setp entry in HKLM which will add the required
HKCU key for automatic launching of the GUI on startup
- The HKCU entry for a user will only be added once when the user logs in
after a new installation
- As the startup key is in HKCU, the user can change it without admin rights
- For silent installs use SELECT_LAUNCH=0/1. It is selected by default
=> Use active-setup registry entry to add GUI to startup menu of users

windows-nsis/openvpn.nsi
This fixes the four original issues identified in https://github.com/OpenVPN/openvpn-build/issues/59
=> Fix issue #59

windows-nsis/openvpn.nsi
=> fix for trac#806

windows-nsis/openvpn.nsi
see http://nsis.sourceforge.net/Reference/SetCompressor for more details
=> added /SOLID

generic/build.vars
URL: https://community.openvpn.net/openvpn/ticket/325
=> Enable ASLR/DEP by default

.appveyor.yml
there're still unresolved things like
a) what to do with missing "man2html"
b) what to do with missing makensis 
but, I beleive, it is already useful
=> initial AppVeyor support

.travis.yml
- removed "cache: apt", which never worked
- changed repo management to apt-add-repository
=> travis-ci: couple of improvements

generic/gentoo.config-0.9.8
this is the same as antonio/fix-and-aarch64 but without 6ae9644
=> fix and aarch64 bis

.appveyor.yml, README, generic/build, msvc/README, msvc/build-env.bat, msvc/build.bat
This patch enables building openvpn with Visual Studio 2017.
VS2017 build is added to AppVeyor.
=> win: support for Visual Studio 2017

.appveyor.yml
=> appveyor: collect build artifacts for mingw jobs

.appveyor.yml, msvc/README, msvc/build-env.bat, msvc/build.bat
Also bump dependency versions.
=> msvc: make Visual Studio build use OpenSSL 1.1.1

windows-msi/msi.wxs
=> msi: update all files on reinstall regardless of versions

msvc/build-env.bat, msvc/build.bat
Thou 2.6 is targeting to replace MSVC with vcpkg & CMake, lets still keep things tidy, clean and working here.
=> Various msvc build fixes

.gitignore, README.rst, windows-msi/README.rst, windows-msi/build-and-package-env-sample.ps1, windows-msi/build-and-package.ps1, windows-msi/build-openvpn-gui.ps1, windows-msi/msbuild-x64.bat, windows-msi/msbuild-x64_arm64.bat, windows-msi/msbuild-x64_x86.bat, windows-msi/sign-binaries.bat
The script runs exactly the same things as Buildbot Windows workers do
=> windows-msi: add full Windows build and packaging script

windows-msi/bump-version.m4.ps1
This is required for providing Windows snapshot packages
=> windows-msi: introduce a Powershell script for bumping version.m4

windows-msi/version.m4
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>
=> Update Easy-RSA to version 3.1.0

windows-msi/version.m4
=> windows-msi: download Wintun MSMs from safe location

windows-msi/version.m4
=> Update dco-win driver version to 0.8.1

windows-msi/version.m4
=> Bump ovpn-dco version to 0.8.2

windows-msi/version.m4
=> Bump version to 2.5.8-I601

windows-msi/vcpkg-ports/openssl/portfile.cmake, windows-msi/vcpkg-ports/openssl/vcpkg.json
=> Bump OpenSSL to 1.1.1s

windows-msi/version.m4
=> Bump tap-windows6 driver to 9.24.8 (release/2.5)

.github/workflows/build.yaml
=> GitHub Actions: don't upload t_client logs to remote

windows-msi/version.m4
=> Bump version to 2.5.8-I604

windows-msi/version.m4
=> Bump ovpn-dco to 0.8.3

windows-msi/bump-version.m4.sh
=> bump-version.m4.sh: Fix to generate actual UUIDs

debian-sbuild/scripts/freight-add-many.py
This was done some time ago, but seems we never
committed it.
=> debian-sbuild: port freight-add-many.py to Python 3

windows-msi/doc/config-auto/README.txt.in, windows-msi/doc/config/README.txt.in
=> Update README.txt.in in config and config-auto

.github/workflows/build.yaml
Official download location is very unreliable.
=> GHA: download strawberry perl from our own mirror

windows-msi/version.m4
=> Bump ovpn-dco-win to 0.9.0

windows-msi/version.m4
Change-Id: I17d7a3e886622d6870ee54e7591b4aac90fd7078
=> msi: bump ovpn-dco-win to 0.9.3

windows-msi/version.m4
Change-Id: I5b76ed7342f3fceccd957bd806990067e49e4e9b
=> Bump TAP driver to 9.25.0

renovate.json
=> Renovate: group GHA update together and move them to weekly schedule

debian-sbuild/openvpn/bookworm/debian/patches/series, debian-sbuild/openvpn/bullseye/debian/patches/series, debian-sbuild/openvpn/focal/debian/patches/series, debian-sbuild/openvpn/jammy/debian/patches/series, debian-sbuild/openvpn/mantic/debian/patches/series
=> debian-sbuild: disable systemd.patch

release/full-release-build.sh, release/source-build.sh, release/vars.example, release/version-and-tags.sh
A separate new MSI builds are rare case
And it's easy to forget some steps
Better to have it scripted and have the condition what we would like to build
=> MSI build only

windows-msi/msi.wxs
We've switched to MSI in 2.5, so everyone
should have upgraded by now.
GitHub: #842
=> msi: remove NSIS upgrade support

windows-msi/msi.wxs
Since OpenVPN service user doesn´t have write access
to %PROGRAMFILES%, change log dir to
C:\ProgramData\OpenVPN\Log
=> msi: change log directory for persistent connections

windows-msi/msi.wxs, windows-msi/script/RegisterEventSource.js
This enables OpenVPNService, running under limited virtual service account, to log to event log.
GitHub: https://github.com/OpenVPN/openvpnserv2/pull/27
=> msi: create event source for OpenVPNService
